name: Publish package 📦 to PyPI

on:
  release:
    types: [created]

env:
  SKIP_REMOTE_VERSION_CHECK: true


jobs:
  build:
    uses: ./.github/workflows/build.yml


  check-version:
    needs: build
    name: Check the version of the distribution 📦
    runs-on: ubuntu-latest

    steps:
      - name: Check latest version on PyPI
        if: ${{ env.SKIP_REMOTE_VERSION_CHECK != 'true' }}
        uses: KevinRohn/gh-action-pypi-package-version@v1
        id: check-version
        with:
          package-name: markdown-translate-ai
          endpoint: pypi

      - name: Check if the version is already published
        if: ${{ env.SKIP_REMOTE_VERSION_CHECK != 'true' }}
        run: | #shell
          local_version=${{ needs.build.outputs.package-version }}
          testpypi_latest_version=${{ steps.check-version.outputs.latest-version }}
          testpypi_release_versions=${{ steps.check-version.outputs.all-releases }}

          release_versions=(${testpypi_release_versions//[\[\]]/' '})

          # Check if local version exists in release versions
          if [[ " ${release_versions[@]} " =~ " ${local_version} " ]]; then
            echo "::warning::The package version ${local_version} is already published to TestPyPI."
            exit 1
          fi

  publish-to-pypi:
    name: >-
      Publish to PyPI
    if: startsWith(github.ref, 'refs/tags/') 
    needs: [build, check-version]
    runs-on: ubuntu-latest

    environment:
      name: pypi
      url: https://pypi.org/p/markdown-translate-ai
    
    permissions:
      id-token: write

    steps:
    - name: Download all the dists
      uses: actions/download-artifact@v4
      with:
        name: python-package-distributions
        path: dist/

    - name: Publish distribution 📦 to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
